FROM unleashorg/unleash-proxy

ENV PORT 4242
EXPOSE 4242

COPY ./scripts/load_secrets_and_run.sh load_secrets_and_run.sh

ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh", "./load_secrets_and_run.sh"]

CMD ["/bin/sh" "-c" "./server.sh"]
