---
version: '2'
services:
  artsy-unleash:
    environment:
      - HTTP_PORT=8080
      - DATABASE_URL=postgresql://postgres:@artsy-unleash-postgres/unleash_development
      - DATABASE_SSL=false
    build:
      context: ../
    ports:
      - 8080:8080
    depends_on:
      - artsy-unleash-postgres
  artsy-unleash-postgres:
    image: postgres:12.5-alpine
    environment:
      - POSTGRES_DB=unleash_development
      - POSTGRES_HOST_AUTH_METHOD=trust
  artsy-unleash-proxy:
    image: unleashorg/unleash-proxy
    environment:
      - PORT=4242
      - UNLEASH_API_TOKEN=REPLACE_ME
      - UNLEASH_PROXY_SECRETS=some-secret
      - UNLEASH_URL=http://artsy-unleash:8080/api/
    ports:
      - 4242:4242
    depends_on:
      - artsy-unleash
